### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by ArchontisKostis** [ArchontisKostis/SimpleComponents#1]
There are some broken links on the markdown files

**Comment by maddy020** [comment]
Hey @ArchontisKostis 
I would like to contribute in this issue
Please give me some more details

**Comment by ArchontisKostis** [comment]
Hey @maddy020,
Thank you for your interest in contributing to the project! I really appreciate your help. 

To give you more context and help you get started, here is some additional information about the issue:

Most of the broken links are located on the `Reference.md` file inside the `docs/` folder, I checked the other markdown files on the repository and I think they are good. You could also check them if you want, just to make sure.

To fix a broken link, you can do the following:
1. Identify the broken link by clicking on it and seeing if it leads to a 404 error page.
2. Check the link to see if it is typed correctly and if the destination webpage is still available.
3. If the link is typed correctly but the destination webpage is no longer available, you can try to find an alternative webpage that covers the same information.
4. If the link is not typed correctly, you can correct the spelling and syntax of the link.
5. Test the fixed link to make sure it is working correctly.

The library also has a [contributing guide](https://github.com/ArchontisKostis/SimpleComponents/blob/main/docs/CONTRIBUTING.MD) that you can check out for more information on how to contribute to the project.

If you have any questions or need further clarification, don't hesitate to ask.

Thanks again for your interest and we look forward to your contributions!

**Comment by maddy020** [comment]
I don't see any broken link in Reference.md 
Instead I found in readme.md a broken link which shows 404 err page
